# Generated by Django 4.1.1 on 2023-03-20 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_profile',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='employee_profile.department'),
        ),
    ]
