# Generated by Django 4.1.1 on 2023-03-21 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_profile', '0004_employee_profile_created_employee_profile_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
